name: Ежедневный дайджест новостей

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run news digest
      env:
        HFTOKEN: ${{ secrets.HFTOKEN }}
        TGBOT: ${{ secrets.TGBOT }}
        TGCHAT: ${{ secrets.TGCHAT }}
      run: python news_digest.py
  TGCHATID: ${{ secrets.TGCHATID }}
      run: python news_digest.py
