name: Ежедневный дайджест новостей

on:
  schedule:
    - cron: '0 5 * * *'  # Каждый день в 05:00 UTC (08:00 МСК)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run news digest
      env:
         HFTOKEN: ${{ secrets.HFTOKEN }}
  TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
  TGCHATID: ${{ secrets.TGCHATID }}
      run: python news_digest.py
