name: Ежедневный дайджест новостей

on:
  schedule:
    - cron: '0 5 * * *'  # Каждый день в 05:00 UTC (08:00 МСК)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run news digest
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python news_digest.py

    - name: Upload digest as artifact
      uses: actions/upload-artifact@v3
      with:
        name: daily-digest
        path: last_digest.md
